spring:
  application:
    name: security-02-db-login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springsecurity


mybatis:
  configuration:
    # \u5F00\u542F\u9A7C\u5CF0\u6620\u5C04
    map-underscore-to-camel-case: true
  type-aliases-package: cn.believesun.pojo
