spring:
  application:
    name: security-04-captcha-login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springsecurity


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.believesun.pojo
